
question_list = {

    "Automotive": [

        "Which three companies led the sales growth in the auto industry in January?",
        "How did Maruti Suzuki's sales in January compare to the year-ago period?",
        "What was Hyundai Motor India's sales achievement in January, and how did it compare to the same period last year?",
        "How did Tata Motors, Mahindra, Toyota Kirloskar Motor, and Honda Cars India perform in terms of sales in January?",
        "What are the expectations for the auto industry's momentum in 2024 according to Hyundai Motor India's COO?",
        "How did the two-wheeler and commercial vehicle segments perform in January?",
        "What factors are affecting the farm equipment sector's sales, according to Mahindra & Mahindra's President – Farm Equipment Sector?",
        "What are the EPA's proposed pollution regulations aimed at for 2032 in terms of electric vehicle sales?",
        "How do the proposed EPA regulations plan to impact greenhouse gas emissions from transportation?",
        "What are the challenges associated with scaling up electric vehicle production and infrastructure according to the document?",
        "What are the projections for electric vehicle sales by 2030 without the new EPA rules, and how do the rules impact these projections?",
        "How does the Biden administration plan to secure raw materials for electric vehicle batteries and what incentives are offered?",
        "What is the expected impact of the EPA's regulations on carbon emissions over the next three decades?",
        "How might the EPA's proposed rules be challenged in court, and why might they be considered legally durable?",
        "What prompted the European Commission to propose a delay in tariffs on electric vehicles traded between the UK and EU?",
        "How do the proposed tariff delays aim to support the car industry within the EU bloc?",
        "What were the original rules of origin for cars to qualify as tariff-free, and how are they related to the electric vehicle market?",
        "Why were the tariffs considered likely to lead to huge costs for the car industry?",
        "What impact would the delayed tariffs have on the cost of electric vehicles and the industry's competition with countries like China?",
        "How does the European Commission plan to support European battery manufacturers in light of the tariff delay?",
        "What are the implications of the tariff delay for UK electric car production and the establishment of gigafactories?",
        "What is the significance of the clause added to the Brexit trade deal concerning the duration of the tariff extension?",
        "What initiatives has the Indian government announced in the 2024 budget to support the electric vehicle (EV) ecosystem?",
        "How does the government plan to encourage the greater adoption of e-buses in public transport networks?",
        "What opportunities for entrepreneurship and employment does the 2024 budget aim to provide in the EV sector?",
        "What tax exemptions and subsidies were introduced in the previous budget to support the manufacturing of lithium-ion cells and EV batteries?",
        "What is the government's target for EVs' share in new vehicle sales by 2030, and how do current sales compare?",
        "What are the projections for India's electric vehicle market by 2030 in terms of sales and job creation?",
        "What are the new electric models Nissan has committed to manufacturing in Sunderland?",
        "How many jobs is the investment in new electric models expected to preserve at the Sunderland site?",
        "What is the estimated value of the investment Nissan plans to make for its electric vehicle production in Sunderland?",
        "How does the UK government's Automotive Transformation Fund support Nissan's investment in electric vehicles?",
        "What significance does Nissan's battery plant in Sunderland hold for the UK's electric vehicle industry?",
        "How do post-Brexit trading rules affect the electric vehicle industry, particularly regarding tariffs and sourcing of components?",
        "What are Nissan's plans regarding electric vehicle production by 2030, and how does this align with the UK's automotive industry trends?",

    ],

    "Healthcare":[

        "How does early detection impact the prognosis of breast cancer?",
        "What are the most common early signs of breast cancer?",
        "What is personalized screening, and how does it improve the prognosis and mortality rates of breast cancer?",
        "How has the treatment landscape for breast cancer evolved in recent years?",
        "What role does immunotherapy play in the treatment of advanced forms of breast cancer?",
        "How do newer therapies like endocrine therapy contribute to preventing relapse and recurrence of breast cancer?",
        "Why is targeted screening and treatment crucial, especially for Indian women with breast cancer?",
        "How might emerging technologies and robust treatment options revolutionize cancer care and improve quality of life?",
        "How does the aging population trend in India by 2050 highlight the need for specialized geriatric care?",
        "In what ways does Apollo ProHealth’s geriatric program aim to address the unique challenges faced by India’s elderly population?",
        "How does geriatric care in India compare with that in Western countries, particularly in terms of integration into the healthcare system?",
        "What are the significant physical and psychological impacts of falls in older adults, and how does Apollo ProHealth’s program address these?",
        "What sets Apollo ProHealth’s geriatric program apart in dealing with the social, mental, and physical aspects of elderly well-being?",
        "How do comprehensive evaluations and assessments in Apollo ProHealth’s program contribute to promoting healthy aging?",
        "What are the key expectations from Union Budget 2024 as shared by healthcare industry leaders with ETHealthworld?",
        "How does the budget aim to address the needs of India's young population according to Poonam Muttreja?",
        "What structural shift is Shyamal Santra suggesting for India's Public Health System in Budget 2024?",
        "How does the HPV vaccine contribute to the prevention of cervical cancer?",
        "What are the recommended ages and dosage schedules for HPV vaccination in India?",
        "How does programmatic accessibility affect the distribution of cervical cancer services in densely populated countries like India?",
        "What role do healthcare professionals play in advocating for HPV vaccination?",
        "How does male HPV vaccination contribute to herd immunity and the prevention of various cancers?",
        "What are the benefits of training healthcare professionals on HPV vaccination communication?",
        "Why is a comprehensive approach involving vaccination, screening, and awareness crucial in addressing cervical cancer in India?",
        "How do public-private partnerships enhance the efforts towards cervical cancer elimination by 2030?",
        "Why are women more likely than men to develop autoimmune diseases, according to recent research?",
        "What role does the X chromosome play in the gender bias of autoimmune diseases?",
        "How does the process of X-chromosome inactivation contribute to autoimmunity?",
        "What are autoantibodies, and how do they relate to autoimmune disorders in the context of Xist RNA?",
        "What was the significant finding from Dr. Howard Chang's research on skin-related autoimmune disorders?",
        "How might the Xist RNA and associated protein clumps activate the immune system?",
        "What are the implications of the Stanford study's findings for diagnosing autoimmune diseases in women?",
        "How did male lab mice engineered to produce Xist RNA react in the study?",
        "What potential new avenue for autoimmune disease diagnosis does the Stanford study suggest?"

    ],
    "Lifescience":[

        "What recent study expanded upon the anti-cancer activity of sRNA from Cantharellus cibarius and investigated the potential of sRNA from Boletus edulis and Agaricus bisporus?",
        "How do the anti-cancer properties of sRNAs from different mushrooms compare according to the study?",
        "Describe the historical context of mushroom use in cancer research.",
        "What are the potential benefits of identifying the mechanisms of action of sRNAs in mushrooms for the medical and nutritional industries?",
        "In the study, which two mushroom species were newly tested for their sRNA's anti-cancer efficacy, and where were they harvested?",
        "How were sRNAs and miRNAs extracted for the study, and what methods were used to evaluate their efficacy?",
        "What were the key findings regarding the anti-cancer properties of sRNAs and miRNAs from Boletus edulis and Agaricus bisporus?",
        "Explain the significance of the study's findings on the potential use of mushrooms as sources of anti-cancer agents.",
        "What chemical in the blood, identified by Cambridge scientists, is raised by fasting and inhibits inflammation?",
        "In the study published in Cell Reports, what connection did researchers find between fasting, arachidonic acid levels, and inflammation?",
        "How does the study suggest fasting might mimic some beneficial effects of drugs like aspirin?",
        "What is the role of the NLRP3 inflammasome in the body's immune system, and how does arachidonic acid affect it according to the research findings?",
        "Describe the methodology used by Professor Bryant and his colleagues in studying the effects of fasting on inflammation.",
        "What potential long-term health benefits of regular fasting are hinted at by the study's findings?",
        "How does the study contribute to understanding the relationship between a high-calorie diet, inflammasome activity, and chronic diseases?",
        "Explain the 'yin and yang effect' mentioned by Professor Bryant in the context of inflammasome activity and diet.",
        "What unexpected clue does the study offer about the way non-steroidal anti-inflammatory drugs (NSAIDs) like aspirin work?",
        "Why is aspirin cautioned against for reducing the risk of long-term diseases without medical guidance  ?",
        "What is the main advantage of the new precision-targeted delivery method for CRISPR-Cas9 developed at the University of California, Berkeley?",
        "How does the innovative delivery method developed by Jennifer Doudna's lab aim to improve CRISPR gene therapies for blood diseases?",
        "Describe the role of enveloped delivery vehicles (EDVs) in the targeted gene editing process discussed in the document.",
        "How did Jennifer Hamilton and her colleagues demonstrate the potential of their carrier method for in vivo gene editing?",
        "What is the significance of using multiplexing targeting molecules in the context of CRISPR-Cas9 genome editing?",
        "Explain how the study aimed to replicate an ex vivo CRISPR CAR T-cell therapy in vivo and its implications for cancer treatment.",
        "What challenges does the new gene editing method address in terms of efficiency and specificity?",
        "How does the research contribute to reducing the cost and increasing the accessibility of gene therapies?",
        "What is the name of the new microscopy technology developed by researchers at Brigham and MIT for analyzing brain tissue?",
        "How does decrowding expansion pathology (dExPath) enhance the imaging of nanometer-sized structures or cell populations in brain tissue?",
        "What are the main advantages of dExPath over traditional super-resolution microscopy techniques according to Pablo Valdes, MD, PhD?",
        "Describe the role of Ed Boyden, PhD, and E. Antonio Chiocca, MD, PhD, in the development of dExPath.",
        "How does dExPath improve the penetration of antibodies for staining proteins in brain tissue?",
        "What types of brain tissues were tested with dExPath to validate its effectiveness?",
        "Discuss the significance of dExPath in revealing aggressive features in tumors previously classified as 'low-grade.'",
        "What are the potential diagnostic and patient outcome improvements anticipated by the use of dExPath in neuro-oncology?",
    ],

    "Manufacturing":[

        "What regions in the United States are emerging as new centers of innovation and high-tech manufacturing?",
        "How does the University of Tennessee contribute to America's high-tech manufacturing sector?",
        "What is the significance of the Blue Oval City investment in Tennessee?",
        "Describe Vanderbilt University's initiative to boost AI technology in traffic control.",
        "What are the key strategies shared by up-and-coming innovation engines in the U.S. for high-tech-driven growth?",
        "How is South Carolina building a new economy around automotive manufacturing, aerospace, and next-generation energy industries?",
        "What unique educational programs has Clemson University launched to support the automotive and energy industries?",
        "Explain the role of Purdue University in catalyzing a semiconductor ecosystem in Indiana.",
        "What is the 'Competitiveness Conversations Across the County' initiative by the Council’s National Commission on Innovation and Competitiveness Frontiers?",
        "How do partnerships between universities, industry, and government contribute to the development of high-tech manufacturing hubs in America?",
        "What is the primary goal of the Biden Administration's promotion of hydrogen in the U.S.?",
        "How does the proposed federal tax credit aim to encourage the production of green hydrogen?",
        "What challenges do companies face in obtaining the maximum benefit from the Clean Hydrogen Production Credit?",
        "How do the proposed rules for the federal tax credit compare with Europe's approach to clean hydrogen production?",
        "What are the main criticisms of the proposed rules by companies like Plug Power and Cummins' Accelera?",
        "Describe the impact of the proposed rules on the U.S.'s progress toward climate goals according to industry stakeholders.",
        "What are the potential benefits of clean hydrogen for industries under pressure to reduce greenhouse gas emissions?",
        "How does the proposed 45V tax credit's implementation process involve public and federal agency input?",
        "What was Senator Joe Manchin's critique regarding the proposed hydrogen production tax credit rules?",
        "Despite the criticism of the proposed tax credit rules, how did the market react to Plug Power's shares?",
        "What is the main achievement of Concrete.ai in terms of emissions reduction and cost savings per cubic yard of concrete?",
        "How does cement contribute to global carbon dioxide emissions, and why is reducing cement in concrete significant for the environment?",
        "Describe the approach taken by Concrete.ai to optimize concrete mixes. What role does generative AI play in this process?",
        "How does Concrete.ai's Concrete Copilot technology contribute to the construction industry, and what are its commercial milestones as mentioned in the document?",
        "What are some innovative companies and technologies mentioned that are working towards reducing the carbon footprint of concrete and cement?",
        "How do new regulations, such as the Inflation Reduction Act and New York state's Buy Clean Concrete program, impact the construction industry's approach to reducing carbon emissions?",
        "Explain the potential of Concrete.ai's technology in validating green cement and other low-carbon construction materials.",
        "Who are the key individuals behind Concrete.ai, and what inspired their work in reducing the carbon footprint of concrete?",
        "What significant results has Concrete.ai achieved in its field tests, according to the document?",
        "How is Concrete.ai's technology being used in practice by companies like VCNA Prairie Materials, and what are the benefits seen?",
        "What percentage of manufacturing and distribution executives have implemented AI on their factory floors as of Q3 2023?",
        "How does ABB utilize AI to enhance sustainability and operational efficiency in industrial settings?",
        "Describe the role of AI in emissions monitoring and the innovative approach used by ABB.",
        "How has Fluke Reliability incorporated AI into its preventive maintenance solutions, and what are the results of its partnership with Cargill Incorporated?",
        "What is the significance of machine learning in reducing waste for small and medium-sized manufacturers, as demonstrated by Amatrium Inc.?",
        "How does the document describe the future of AI in manufacturing over the next decade?",
        "What are the challenges and opportunities identified for democratizing AI technology in manufacturing?",
        "How does the concept of AI as an 'inference engine' differ from traditional binary logic, according to Mark P. Mills?",
        "In what ways are digital solutions enabling manufacturers to manage power consumption more efficiently in the context of decarbonization?",
        "What example demonstrates the potential of AI to predict machine failures and improve asset management, as highlighted by Fluke Reliability's work?",
        "What trend is anticipated to continue in 2024 regarding the reshoring of manufacturing operations to the United States?",
        "How does the CHIPS Act influence the manufacturing industry's reshoring efforts?",
        "What prediction is made about the electric vehicle (EV) market's fluctuations in 2024?",
        "How is the integration of AI into manufacturing processes expected to evolve in 2024, particularly regarding shop-floor applications?",
        "What challenges related to workforce engagement and retention are manufacturers expected to face in 2024?",
        "How is manufacturing positioned as a potential area of bipartisan agreement in an election year?",
        "What strategies are suggested for manufacturers to prepare for the unpredictability of 2024?",
        "How is the concept of sustainability predicted to influence manufacturing strategies, especially in the EV sector?",
        "What role does artificial intelligence play in non-production aspects of manufacturing, such as marketing and sales?",
        "How might changes in workforce demographics and attitudes impact manufacturing industry practices in 2024?"

    ],

    "Public Sector": [

        "What is the predicted total profit of public sector banks in India for FY2024?",
        "How does the current financial year's first-half profit of public sector banks compare to the full-year projection?",
        "What factors are expected to drive the profitability of banks in the coming months?",
        "How has the Reserve Bank of India (RBI) revised India's growth projection, and what impact does this have on the banking sector?",
        "What challenges are associated with the slower growth of deposits compared to credit growth?",
        "How has the credit growth rate changed from the previous year, according to the latest RBI Bulletin?",
        "What is the RBI's stance on interest rates in the near future?",
        "How have Non-Performing Assets (NPAs) changed over the last three years according to RBI data?",
        "What major development occurred in the banking sector regarding leadership at Kotak Mahindra Bank?",
        "What steps are being taken to address cyber security and online financial frauds in the banking sector?",
        "How much has the government allocated for the procurement of electric buses in the interim Budget?",
        "What is the total allocation for metro projects in the interim Budget, and how does it compare to the previous year's allocation?",
        "What is the Pradhan Mantri Awas Yojana (Urban), and how much funding has it received in the interim Budget?",
        "Describe the Prime Minister Street Vendor's AtmaNirbhar Nidhi (PM SANNidhi) scheme and its allocation in the interim Budget.",
        "How has the allocation for the Smart Cities Mission in the interim Budget changed compared to the 2023-24 General Budget?",
        "What is the outlay and duration of the PM-eBus Sewa scheme, and how will the funding be distributed between the Centre and the states?",
        "What urban transformation initiatives did the Union Finance Minister Nirmala Sitharaman highlight in her interim Budget speech?",
        "When was the country's first Regional Rapid Transit System (RRTS) flagged off, and what is its name?",
        "What are the expected benefits of expanding metro rail and NaMo Bharat trains in large cities, according to Sitharaman?",
        "According to the Union Ministry of Housing and Urban Affairs, how many passengers ride metro systems per day in the country?",
        "What is the total capital expenditure announced for the fiscal year 2024, and how does it compare to the previous fiscal year?",
        "What fiscal deficit target has the government set for the fiscal year 2024, and what is the goal for FY26?",
        "How has the government proposed to address old disputed direct tax demands up to the fiscal year 2009-2015?",
        "What new routes are planned under the Udan Scheme to improve air connectivity?",
        "How much has been allocated to the Railways, and what are the new economic corridors announced?",
        "Describe the focus of the Production Linked Incentive (PLI) scheme based on the budget allocation.",
        "What are the key highlights related to agriculture and farmer support in the budget?",
        "How much funding has been allocated for healthcare, and what new initiatives are announced?",
        "What is the government's plan for renewable energy and electricity subsidy to households?",
        "Discuss the government's vision for the next five years as stated in the budget document.",
        "What is Jayanth R Varma's position on the future of private capital expenditure in India?",
        "How has the government's role in investment influenced private capital expenditure in recent years, according to Varma?",
        "What factors are contributing to the increase in capacity utilization mentioned by Jayanth R Varma?",
        "How does Varma view the potential for private sector investments to be crowded in by large public sector infrastructure investments?",
        "What is Jayanth R Varma's outlook on India escaping the middle-income trap, and what growth rate does he deem necessary?",
        "How does Varma perceive India's democratic polity in terms of responding to the needs and aspirations of its people?",
        "Can you explain the concept of the middle-income trap as described in the document?",
        "How are middle-income countries classified according to the World Bank, and what challenges do they face?",
        "What measures announced in the interim budget were welcomed by the tourism and hospitality industry?",
        "How much has the budgetary allocation to the tourism ministry increased in the financial year 2024-25 compared to the previous year?",
        "What is the significance of the finance minister's announcement regarding the development of iconic tourist centers and improving tourism infrastructure on islands?",
        "How do industry insiders view the potential impact of the interim budget announcements on foreign tourist arrivals and the hospitality industry?",
        "What are the expectations from the actual budget in July regarding international promotion and development of iconic destinations?",
        "How does the interim budget address the aspirations of the middle class for travel and exploration, including spiritual tourism?",
        "What role do interest-free loans to states for creating iconic tourist destinations play in the interim budget?",
        "What are the concerns expressed by the Indian Association of Tour Operators (IATO) regarding the interim budget's impact on attracting tourists to the country?",
        "Describe the interim budget's multipronged approach to tourism and its expected multiplier effect across related sectors"

    ]

}